name: zero2prod-github-actions

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: cargo build --verbose
        working-directory: server

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: rustup component add rustfmt

      - name: fmt
        run: cargo fmt --all -- --check
        working-directory: server

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: rustup component add clippy

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: server

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: cargo test --all -- --nocapture
        working-directory: server

  cov:
    runs-on: ubuntu-latest

    steps:
      - run: rustup component add llvm-cov

      - name: cov
        run: cargo llvm-cov
        working-directory: server
